### PR TITLE
issue: "Fix setValue function in Board #65"

### PR DESCRIPTION
**Pull request by nandofromthebando**
There was a reversal of row and column values in the Board class as well as piece controller class in the setValue method. I went through and switched them into the correct positions where they needed to be.

### CODE REVIEW

**Comment by nandofromthebando** [comment]
Also added a little more documentation where there was little or none. Hopefully this helps and makes things easier, I tried to be as detailed as possible!

**Comment by Zeran719** [comment]
could you assign this to me?

**Comment by MrMystery10-del** [comment]
> could you assign this to me?

sure, assigned

**Comment by Zeran719** [comment]
Thank you for offering me this chance for a beginner. 
I am just curious when this repo was running successfully last time? I have a hard time on building the project, met errors like duplicated classes, trying to fix them but more errors appear. I will be so grateful if you can tell me which version was runnable in the history.
I am so sorry for the inconvenience.

**Comment by jorn-fa** [comment]
last running one should be the one before the change to FX.  The backend should still al work , just the frontend needs to be redone completely.  The person who was going to do the change to FX nuked the whole repo and i had to piece it all together again

**Comment by Zeran719** [comment]
I am sorry to hear that, I really like the idea of this repo because I want to see why I cannot beat AI in the game. 
Maybe rolling back is a good idea. it is so complicated for me so far since I am a beginner but I will see what I can do for this repo if I have spare time. Thank you for your reply.

**Comment by jorn-fa** [comment]
My current personal repo should be ahead of this one. Can't recall as i stopped working on it.  But seing as its getting more animo i might sync it up.   Just don't feel like doing it all alone ;)

**Pull request merged**
