### PR TITLE
Added a Settings Button

### PR DESCRIPTION
**Pull request by lenarduzziadam**
I've Added a settings button to the main menu screen. The button is positioned next to the profile button and allows the user to access the game's settings. Clicking the button triggers the showSettings() method, which is defined in the implementing class. Questions or concerns welcome.

### CODE REVIEW

**Comment by MrMystery10-del** [comment]
Thanks for contributing.

There are a fex things u will need to fix:
- You dont need to comment every single line, what happens in that lines is self explaining, a head comment like u did over the openSettings method is completely fine
- Since openSettings is a abstract method, you will need to implement that method in the core class(which is one click if u use Intellij)
- resourceBundle.getString("settings") will also throw a exception since we not have a keyword called settings in the properties file, but u can add it pretty quick

So i would recommend to first start the application to see if it still works, before pull

**Comment by lenarduzziadam** [comment]
This is a bit embarrassing I could not figure out how to get the application running on my mac.

**Comment by lenarduzziadam** [comment]
Where can i find a link to the discord. I wasnt using Intellij ill try that when I get home from work

**Comment by MrMystery10-del** [comment]
It says you did changes, but i dont see any changes. I only see the changes u already did before which were invalid

**Comment by lenarduzziadam** [comment]
I tried changing the core but then the chess game wouldnt run... so i reverted it, i didnt realize itd come up through github

**Comment by vansh2552** [comment]
@lenarduzziadam can you help me in setting up the code locally?

**Comment by lenarduzziadam** [comment]
Im about to head to work but i can after i get off

**Comment by vansh2552** [comment]
That would be great :)

**Comment by lenarduzziadam** [comment]
What do you need help with specifically?

**Comment by MrMystery10-del** [comment]
@lenarduzziadam btw did you got it running?

**Pull request closed without merging**
